<dl>
    <dt><?= $this->translate('Title') ?></dt>
    <dd><?= $this->entity->getTitle() ?></dd>
    <dt><?= $this->translate('Body') ?></dt>
    <dd><?= $this->entity->getBody() ?></dd>
</dl>
<p>
    <a href="<?= $this->url(array('action' => 'show', 'id' => $this->entity->getId())) ?>" title="<?= $this->translate('Show Post') ?>"><?= $this->translate('Show Post') ?></a>
    <a href="<?= $this->url(array('action' => 'edit', 'id' => $this->entity->getId())) ?>" title="<?= $this->translate('Edit Post') ?>"><?= $this->translate('Edit Post') ?></a>
    <a href="<?= $this->url(array('action' => 'delete', 'id' => $this->entity->getId())) ?>" title="<?= $this->translate('Delete Post') ?>"><?= $this->translate('Delete Post') ?></a>
</p>
