<?php echo $this->doctype() ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headStyle() ?>
    </head>

    <body>
        <?php if(!empty($this->messages)) : ?>
            <ul>
                <?php foreach($this->messages as $message) : ?>
                    <li><?= $this->escape($this->translate($message)) ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?= $this->layout()->content; ?>
    </body>
</html>
