<h1><?= $this->translate('default.post.list.title') ?></h1>
<p>
    <a href="<?= $this->url(array('action' => 'new')) ?>" title="<?= $this->translate('default.post.new.link') ?>"><?= $this->translate('default.post.new.link') ?></a>
</p>
<?= $this->partialLoop('post/partialPost.phtml', $this->posts) ?>
<p>
    <a href="<?= $this->url(array('action' => 'new')) ?>" title="<?= $this->translate('default.post.new.link') ?>"><?= $this->translate('default.post.new.link') ?></a>
</p>
