<dl>
    <dt><?= $this->translate('default.post.entity.title') ?></dt>
    <dd><?= $this->entity->getTitle() ?></dd>
    <dt><?= $this->translate('default.post.entity.body') ?></dt>
    <dd><?= $this->entity->getBody() ?></dd>
</dl>
<p>
    <a href="<?= $this->url(array('action' => 'show', 'id' => $this->entity->getId())) ?>" title="<?= $this->translate('default.post.show.link') ?>"><?= $this->translate('default.post.show.link') ?></a>
    <a href="<?= $this->url(array('action' => 'edit', 'id' => $this->entity->getId())) ?>" title="<?= $this->translate('default.post.edit.link') ?>"><?= $this->translate('default.post.edit.link') ?></a>
    <a href="<?= $this->url(array('action' => 'delete', 'id' => $this->entity->getId())) ?>" title="<?= $this->translate('default.post.delete.link') ?>"><?= $this->translate('default.post.delete.link') ?></a>
</p>
